
import React from 'react';
import { MenuItem, EventItem, GalleryImage } from './types';

export const MENU_DATA: MenuItem[] = [
  // --- BRUNCH MENU ---
  { id: 'br1', name: 'Greek Omelet', price: '$15', description: '3 eggs, spinach, cherry tomatoes, and feta cheese. Served with house salad & toast.', menuType: 'Brunch', section: 'Breakfast', popular: true },
  { id: 'br2', name: 'Veggie Omelet', price: '$14', description: '3 eggs, mushrooms, peppers, onions, tomatoes, and mozzarella cheese. Served with house salad & toast.', menuType: 'Brunch', section: 'Breakfast' },
  { id: 'br3', name: 'Breakfast Sandwich', price: '$14', description: 'Avocado, egg, and cheese.', menuType: 'Brunch', section: 'Breakfast' },
  { id: 'br4', name: 'Breakfast Wrap', price: '$15', description: 'Scrambled eggs, avocado, spinach, cherry tomatoes, and feta cheese.', menuType: 'Brunch', section: 'Breakfast' },
  { id: 'br5', name: 'Avocado Toast', price: '$16', description: 'Two eggs any style, lemon zest, mix greens, cherry tomatoes, and lemon vinaigrette.', menuType: 'Brunch', section: 'Breakfast', popular: true },
  { id: 'br6', name: 'Classic Americano', price: '$15', description: 'Two eggs any style, bacon, ham, or sausage, served with potatoes and toast.', menuType: 'Brunch', section: 'Breakfast' },
  { id: 'br7', name: 'Ribeye', price: '$22', description: '8oz ribeye, two eggs any style, served with potatoes and toast.', menuType: 'Brunch', section: 'Breakfast' },
  { id: 'br8', name: 'French Toast', price: '$14', description: 'French toast with a berry compote, cinnamon, sugar, whipped cream, bananas, and seasonal fruit.', menuType: 'Brunch', section: 'Breakfast' },

  { id: 'cf1', name: 'Espresso', price: '$3.95', description: 'Rich and bold house roast.', menuType: 'Brunch', section: 'Coffee' },
  { id: 'cf2', name: 'Cappuccino', price: '$5.75', description: 'Espresso with airy foam.', menuType: 'Brunch', section: 'Coffee' },
  { id: 'cf3', name: 'Cafe Latte', price: '$5.75', description: 'Classic creamy espresso latte.', menuType: 'Brunch', section: 'Coffee' },
  { id: 'cf4', name: 'Vanilla Latte', price: '$6.50', description: 'Espresso with Madagascar vanilla.', menuType: 'Brunch', section: 'Coffee' },
  { id: 'cf5', name: 'Spanish Latte', price: '$6.50', description: 'Sweetened condensed milk latte.', menuType: 'Brunch', section: 'Coffee' },
  { id: 'cf6', name: 'Matcha Latte', price: '$6.50', description: 'Ceremonial grade matcha.', menuType: 'Brunch', section: 'Coffee' },
  { id: 'cf7', name: 'Hot Chocolate', price: '$5.75', description: 'House-made cocoa blend.', menuType: 'Brunch', section: 'Coffee' },
  { id: 'cf8', name: 'Chai Latte', price: '$6.50', description: 'Spiced aromatic tea.', menuType: 'Brunch', section: 'Coffee' },

  { id: 'mm1', name: 'Orange', price: '$9', description: 'Freshly squeezed orange juice and champagne.', menuType: 'Brunch', section: 'Mimosas' },
  { id: 'mm2', name: 'Grapefruit', price: '$9', description: 'Ruby red grapefruit juice and champagne.', menuType: 'Brunch', section: 'Mimosas' },
  { id: 'mm3', name: 'Titos House Bloody Mary', price: '$12', description: 'Our signature spicy house mix.', menuType: 'Brunch', section: 'Mimosas', popular: true },

  { id: 'w1', name: 'Beef Kebab', price: '$17', description: 'U.S.D.A. Choice beef kabob with lettuce, tomatoes, and garlic lemon house dressing rolled in a pita bread.', menuType: 'Brunch', section: 'Wraps' },
  { id: 'w2', name: 'Chicken Kebab', price: '$18', description: 'Famous chicken breast kabob with garlic lemon dressing rolled in a pita bread.', menuType: 'Brunch', section: 'Wraps', popular: true },
  { id: 'w3', name: 'Kofta Kebab', price: '$18', description: 'Grilled ground beef kofta with garlic lemon dressing rolled in a pita bread.', menuType: 'Brunch', section: 'Wraps' },
  { id: 'w4', name: 'Gyro', price: '$17', description: 'Lamb and ground steak gyro with tzatziki sauce rolled in a flat bread.', menuType: 'Brunch', section: 'Wraps' },
  { id: 'w5', name: 'Falafel', price: '$17', description: 'Falafel patties with lettuce, tomatoes, and tahini sauce rolled in a pita bread.', menuType: 'Brunch', section: 'Wraps' },
  { id: 'w6', name: 'Salmon', price: '$19', description: 'Mediterranean seasoned salmon with rice, fattouch salad, grilled onions, yellow squash, and green zucchini in a pita.', menuType: 'Brunch', section: 'Wraps' },
  { id: 'w7', name: 'Chicken Shawarma', price: '$18', description: 'Slow-roasted chicken shawarma with garlic sauce rolled in a pita bread.', menuType: 'Brunch', section: 'Wraps' },

  { id: 'p1', name: 'Chicken Breast Special', price: '$16', description: 'Grilled chicken breast, avocado, sun dried tomato, provolone cheese and pesto sauce on Italian ciabatta bread.', menuType: 'Brunch', section: 'Paninis', image: '/craigrootimaging_GO-339-scaled.jpg' },
  { id: 'p2', name: 'Tuna Avocado', price: '$16', description: 'Tuna, avocado, sun-dried tomatoes, provolone cheese and pesto sauce on Italian ciabatta bread.', menuType: 'Brunch', section: 'Paninis' },
  { id: 'p3', name: 'Turkey', price: '$16', description: 'Sliced turkey breast, avocado, tomato, provolone cheese and pesto sauce on Italian ciabatta bread.', menuType: 'Brunch', section: 'Paninis' },
  { id: 'p4', name: 'Chicken Bacon Chipotle', price: '$16', description: 'Grilled chicken, bacon, tomato, provolone, cilantro and chipotle sauce on Italian ciabatta.', menuType: 'Brunch', section: 'Paninis', popular: true },
  { id: 'p5', name: 'Vegetarian', price: '$16', description: 'Grilled eggplant, spring mix, roasted red peppers, fresh roma tomato, provolone cheese and pesto sauce.', menuType: 'Brunch', section: 'Paninis' },
  { id: 'p6', name: 'Caprese Panini', price: '$16', description: 'Buffalo mozzarella, roma tomatoes, fresh basil and pesto bread.', menuType: 'Brunch', section: 'Paninis' },

  { id: 'hd1', name: 'Babaganoush with Pita', price: '$10', description: 'Roasted eggplant dip.', menuType: 'Brunch', section: 'House Dip' },
  { id: 'hd2', name: 'Hummus with Pita', price: '$9', description: 'Creamy chickpea and tahini dip.', menuType: 'Brunch', section: 'House Dip' },
  { id: 'hd3', name: 'Garlic Paste', price: '$9', description: 'Bold and creamy garlic dip.', menuType: 'Brunch', section: 'House Dip' },
  { id: 'hd4', name: 'Dip Trio', price: '$15', description: 'Babaganoush, Hummus, & Spicy Feta.', menuType: 'Brunch', section: 'House Dip', popular: true },

  { id: 'es1', name: 'Tahini Cup', price: '$.75', description: 'Classic sesame dip.', menuType: 'Brunch', section: 'Extra Sauces' },
  { id: 'es2', name: 'Garlic Dressing', price: '$.75', description: 'House garlic lemon dressing.', menuType: 'Brunch', section: 'Extra Sauces' },
  { id: 'es3', name: 'Green Hot Sauce Cup', price: '$.75', description: 'Our signature spicy green sauce.', menuType: 'Brunch', section: 'Extra Sauces' },

  { id: 's1', name: '2 Eggs', price: '$4.50', description: 'Any style.', menuType: 'Brunch', section: 'Sides' },
  { id: 's2', name: '2 Toast', price: '$4', description: 'White or Whole Wheat.', menuType: 'Brunch', section: 'Sides' },
  { id: 's3', name: 'Seasonal Fruit', price: '$5', description: 'Assorted seasonal harvest.', menuType: 'Brunch', section: 'Sides' },
  { id: 's4', name: 'Home Fries', price: '$4', description: 'Crispy cubed potatoes.', menuType: 'Brunch', section: 'Sides' },
  { id: 's5', name: 'Bacon', price: '$5', description: 'Thick cut applewood smoked.', menuType: 'Brunch', section: 'Sides' },
  { id: 's6', name: 'Sausage', price: '$4', description: 'Pork or Turkey.', menuType: 'Brunch', section: 'Sides' },
  { id: 's7', name: 'Avocado', price: '$4.50', description: 'Freshly sliced half.', menuType: 'Brunch', section: 'Sides' },
  { id: 's8', name: 'French Fries', price: '$4', description: 'Classic golden fries.', menuType: 'Brunch', section: 'Sides' },
  { id: 's9', name: 'Falafel Patty', price: '$10', description: 'Two house-made falafels.', menuType: 'Brunch', section: 'Sides' },
  { id: 's10', name: 'Dolmas (6)', price: '$12', description: 'Grape leaves stuffed with rice.', menuType: 'Brunch', section: 'Sides' },
  { id: 's11', name: 'Spicy Potatoes', price: '$11', description: 'Cubed potatoes with mediterranean spices.', menuType: 'Brunch', section: 'Sides' },

  // --- LUNCH/DINNER MENU ---
  { id: 'ls1', name: 'Marinated Olives', price: '$9', description: 'Fennel seed & orange zest.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls2', name: 'Crispy Fried Calamari', price: '$16', description: 'Marinara sauce & herb aioli.', menuType: 'Lunch/Dinner', section: 'Starters', popular: true },
  { id: 'ls3', name: 'Hummus', price: '$9', description: 'Chickpea dip blended with tahini, garlic and lemon juice. Served with warm pita.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls4', name: 'Hummus with Shawarma', price: '$15', description: 'Hummus topped with chicken shawarma. Served with pita bread.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls5', name: 'Spicy Feta', price: '$11', description: 'Creamy feta blended with spicy peppers. Served with pita bread.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls6', name: 'Dip Trio', price: '$15', description: 'Hummus, baba ghanoush and spicy feta served with pita bread.', menuType: 'Lunch/Dinner', section: 'Starters', popular: true },
  { id: 'ls7', name: 'Spicy Potatoes', price: '$11', description: 'Golden, crispy potatoes tossed in our famous green sauce.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls8', name: 'Falafel Patty (6)', price: '$10', description: 'Handcrafted crispy chickpea falafels seasoned with herbs and tahini sauce.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls9', name: 'Dolmas (6) (Grape Leaves)', price: '$12', description: 'Delicate grape leaves stuffed with seasoned rice and herbs.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls10', name: 'Garlic Bread', price: '$8', description: 'Ciabatta bread with herb garlic butter & Parmesan cheese. Served with marinara sauce.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls11', name: 'Baba Ghanoush', price: '$12', description: 'A rich and creamy roasted eggplant dip. Served with pita bread.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls12', name: 'Chicken Shawarma Fries', price: '$14', description: 'Fries topped with mozzarella, chicken shawarma & creamy chipotle sauce.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls13', name: 'Tuscan French Fries', price: '$8', description: 'French fries with garlic, parmesan and parsley.', menuType: 'Lunch/Dinner', section: 'Starters' },
  { id: 'ls14', name: 'Buffalo Wings (8 pieces)', price: '$14', description: 'Served with ranch.', menuType: 'Lunch/Dinner', section: 'Starters' },

  { id: 'lsl1', name: 'Tabbouleh Salad', price: '$11', description: 'A perfect blend of chopped parsley, onions, tomatoes, bulgur, lemon juice, olive oil, and herbs.', menuType: 'Lunch/Dinner', section: 'Salads' },
  { id: 'lsl2', name: 'Greek Salad', price: '$17', description: 'Fresh romaine lettuce, crisp cucumbers, tomatoes, green olives, pepperoncini, feta cheese and our garlic lemon dressing.', menuType: 'Lunch/Dinner', section: 'Salads', popular: true },
  { id: 'lsl3', name: 'Beet Salad', price: '$17', description: 'Roasted rainbow mixed beets, baby lettuce, orange wedge, candy walnuts, feta, honey lemon vinaigrette.', menuType: 'Lunch/Dinner', section: 'Salads' },

  { id: 'lp1', name: 'Chicken Kebob', price: '$21', description: 'Two skewers of chicken breast kabobs marinated in a special blend of Mediterranean spices and herbs.', menuType: 'Lunch/Dinner', section: 'Platters' },
  { id: 'lp2', name: 'Beef Kebob', price: '$24', description: 'Two skewers of marinated U.S.D.A. Choice grilled steak kabobs cooked to perfection.', menuType: 'Lunch/Dinner', section: 'Platters', popular: true },
  { id: 'lp3', name: 'Kafta Kebob', price: '$21', description: 'Two skewers of grilled lean ground beef kofta mixed with fresh parsley, onions and our exceptional blend of Mediterranean seasonings.', menuType: 'Lunch/Dinner', section: 'Platters' },
  { id: 'lp4', name: 'Beef & Chicken Kebob', price: '$24', description: 'One skewer of beef and one skewer of chicken kabob.', menuType: 'Lunch/Dinner', section: 'Platters' },
  { id: 'lp5', name: 'Salmon Kebob', price: '$24', description: 'Two skewers of grilled salmon with onions, yellow squash, green zucchini and mediterranean herbs.', menuType: 'Lunch/Dinner', section: 'Platters' },
  { id: 'lp6', name: 'Spicy Shrimp Kebob', price: '$23', description: 'Two skewers of charbroiled shrimp marinated in a seasoned garlic lemon sauce.', menuType: 'Lunch/Dinner', section: 'Platters' },
  { id: 'lp7', name: 'Vegetarian Platter', price: '$20', description: 'Falafel patties, dolmas, tabouli, and baba ghanouj.', menuType: 'Lunch/Dinner', section: 'Platters' },
  { id: 'lp8', name: 'Gyro Plate', price: '$21', description: 'Slow cooked rotisserie style blend of lamb and ground steak gyro. Served with Tzatziki sauce.', menuType: 'Lunch/Dinner', section: 'Platters' },
  { id: 'lp9', name: 'Lamb Chop Plate', price: '$28', description: 'Perfectly grilled lamb chops seasoned to perfection.', menuType: 'Lunch/Dinner', section: 'Platters', popular: true },
  { id: 'lp10', name: 'Mixed Grill Plate', price: '$27', description: 'A skewer of chicken breast kabob, U.S.D.A. Choice steak kabob, and lean ground beef kofta.', menuType: 'Lunch/Dinner', section: 'Platters', image: '/craigrootimaging_GO-298-scaled.jpg' },
  { id: 'lp11', name: 'Chicken Shawarma Plate', price: '$21', description: 'Tender strips of Mediterranean seasoned chicken shawarma roasted to perfection.', menuType: 'Lunch/Dinner', section: 'Platters' },

  { id: 'lpz1', name: 'Margherita', price: '$19', description: 'Marinara sauce, fresh mozzarella, basil, parmesan cheese, extra virgin olive oil.', menuType: 'Lunch/Dinner', section: 'Pizza' },
  { id: 'lpz2', name: 'Cipolla', price: '$22', description: 'Marinara sauce, Italian sausage, roasted peppers, smoked mozzarella, oregano & red onion.', menuType: 'Lunch/Dinner', section: 'Pizza' },
  { id: 'lpz3', name: 'Bianca', price: '$21', description: 'Mozzarella, ricotta, garlic confit, Sicilian oregano, rosemary, chili flakes.', menuType: 'Lunch/Dinner', section: 'Pizza' },
  { id: 'lpz4', name: 'Funghi', price: '$23', description: 'Mixed mushrooms, fontina cheese, parmesan cheese, extra virgin olive oil.', menuType: 'Lunch/Dinner', section: 'Pizza' },
  { id: 'lpz5', name: 'Diavolo', price: '$22', description: 'Marinara sauce, pepperoni, Calabrian chili, basil, mozzarella & hot honey drizzle.', menuType: 'Lunch/Dinner', section: 'Pizza', popular: true },
  { id: 'lpz6', name: 'Carbonara', price: '$23', description: 'Mozzarella, ricotta, green onion, black pepper, guanciale & farm egg.', menuType: 'Lunch/Dinner', section: 'Pizza' },

  { id: 'lpa1', name: 'Spaghetti with Dungeness Crab', price: '$29', description: 'Garlic, red fresno chili, white wine.', menuType: 'Lunch/Dinner', section: 'Pastas' },
  { id: 'lpa2', name: 'Pappardelle', price: '$24', description: 'Short rib & porcini mushroom ragu.', menuType: 'Lunch/Dinner', section: 'Pastas', popular: true, image: '/craigrootimaging_GO-346-scaled.jpg'},
    { id: 'p1', name: 'Chicken Breast Special', price: '$16', description: 'Grilled chicken breast, avocado, sun dried tomato, provolone cheese and pesto sauce on Italian ciabatta bread.', menuType: 'Brunch', section: 'Paninis', image: '/craigrootimaging_GO-339-scaled.jpg' },
  { id: 'lpa3', name: 'Bucatini Cacio e Pepe', price: '$17', description: 'Black pepper & pecorino romano.', menuType: 'Lunch/Dinner', section: 'Pastas' },
  { id: 'lpa4', name: 'Spaghetti with Little Neck Clams', price: '$22', description: 'Chili garlic butter with white wine.', menuType: 'Lunch/Dinner', section: 'Pastas' },

  { id: 'lk1', name: 'Cheese Pizza', price: '$10', description: 'Simple and delicious.', menuType: 'Lunch/Dinner', section: 'Kids Menu' },
  { id: 'lk2', name: 'Spaghetti with Butter and Cheese', price: '$10', description: 'Classic kid favorite.', menuType: 'Lunch/Dinner', section: 'Kids Menu' },
  { id: 'lk3', name: 'Spaghetti with Tomato Sauce', price: '$10', description: 'Hearty tomato sauce.', menuType: 'Lunch/Dinner', section: 'Kids Menu' },

  { id: 'ld1', name: 'Pistachio Baklava', price: '$6', description: 'Sweet, flaky pastry layered with nuts and honey syrup.', menuType: 'Lunch/Dinner', section: 'Desserts' },
  { id: 'ld2', name: 'NY Cheesecake', price: '$8', description: 'Creamy and rich New York style.', menuType: 'Lunch/Dinner', section: 'Desserts' },
  { id: 'ld3', name: 'Limoncello', price: '$8', description: 'Lemon sponge cake with pistachios.', menuType: 'Lunch/Dinner', section: 'Desserts' },

  // --- DRINKS MENU ---
  { id: 'dk_c1', name: 'Bloody Mary', price: '$12', description: "Tito's Vodka, tabasco, lemon juice and bacon strip.", menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c2', name: 'Clover Club', price: '$12', description: 'Still gin, raspberry puree, lemon juice & egg white.', menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c3', name: 'Espresso Martini', price: '$13', description: "Tito's Vodka, espresso coffee, evil bean liqueur, simple syrup.", menuType: 'Drinks', section: 'Cocktails', popular: true },
  { id: 'dk_c4', name: 'Old Fashioned', price: '$13', description: 'Old grand dad bourbon, sugar cubes & bitters.', menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c5', name: 'House Margarita', price: '$12', description: 'Tequila, lime juice and agave.', menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c6', name: 'Watermelon Marg', price: '$12', description: 'Tequila, lime juice, watermelon, orange liqueur.', menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c7', name: 'Negroni', price: '$13', description: 'Still gin, Campari, and sweet vermouth.', menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c8', name: 'Manhattan', price: '$12', description: 'Whiskey, sweet vermouth, & Angostura bitters.', menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c9', name: 'Cosmopolitan', price: '$13', description: "Tito's vodka, Cointreau, cranberry juice, lemon juice.", menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c10', name: 'Blue Lady', price: '$12', description: 'Still gin, blue curaçao, lemon juice & egg white.', menuType: 'Drinks', section: 'Cocktails' },
  { id: 'dk_c11', name: 'Billionaire', price: '$12', description: 'Empress gin 1908, tonic water, lime juice.', menuType: 'Drinks', section: 'Cocktails' },

  { id: 'dk_ws1', name: 'Cava Freixinet "Blanc de Blancs, Spain"', price: '$9 / $36', description: '', menuType: 'Drinks', section: 'Wine List (Sparkling)' },
  { id: 'dk_ww1', name: '"Daisy" Bieler Family \'23, Washington State', price: '$9 / $36', description: '', menuType: 'Drinks', section: 'Wine List (White)' },
  { id: 'dk_wp1', name: 'Rose Bieler Pere & Fils \'23, Provence, France', price: '$10 / $40', description: '', menuType: 'Drinks', section: 'Wine List (Pink)' },
  { id: 'dk_wr1', name: '"Los Oses" J. Lohr Wines \'22, Paso Robles, California', price: '$9 / $36', description: '', menuType: 'Drinks', section: 'Wine List (Red)' },
  { id: 'dk_wrb1', name: '"Silk & Spice" \'22, Portugal', price: '$9 / $36', description: '', menuType: 'Drinks', section: 'Wine List (Red Blend)' },

  { id: 'dk_db1', name: 'Michelob', price: '$6', description: '', menuType: 'Drinks', section: 'Draft Beer' },
  { id: 'dk_db2', name: 'Modelo', price: '$6', description: '', menuType: 'Drinks', section: 'Draft Beer' },
  { id: 'dk_db8', name: 'Scottsdale Blonde', price: '$6', description: '', menuType: 'Drinks', section: 'Draft Beer' },

  { id: 'dk_bb1', name: 'Michelob', price: '$7', description: '', menuType: 'Drinks', section: 'Bottle Beer' },
  { id: 'dk_bb3', name: 'Stella', price: '$7', description: '', menuType: 'Drinks', section: 'Bottle Beer' },
  { id: 'dk_bb6', name: 'Heineken 0.0', price: '$7', description: 'Non-Alcoholic', menuType: 'Drinks', section: 'Bottle Beer' },

  // --- CATERING MENU (From New Screenshots) ---
  // MEDITERRANEAN FEAST
  { id: 'ct_mf1', name: 'Package A (Per Person)', price: '$19', description: 'Choice of 1 protein, 1 side and 1 salad', menuType: 'Catering', section: 'Mediterranean Feast' },
  { id: 'ct_mf2', name: 'Package B (Per Person)', price: '$23', description: 'Choice of 2 protein, 1 side and 1 salad', menuType: 'Catering', section: 'Mediterranean Feast' },
  { id: 'ct_mf3', name: 'Vegetarian (Per Person)', price: '$19', description: 'Includes grape leaves, hummus, baba ghanoush and tabbouleh', menuType: 'Catering', section: 'Mediterranean Feast' },

  // PROTEIN CHOICE
  { id: 'ct_pc1', name: 'Chicken Kabob', price: '', description: '', menuType: 'Catering', section: 'Protein Choice' },
  { id: 'ct_pc2', name: 'Chicken Shawarma', price: '', description: '', menuType: 'Catering', section: 'Protein Choice' },
  { id: 'ct_pc3', name: 'Beef Kabob', price: '', description: '', menuType: 'Catering', section: 'Protein Choice' },
  { id: 'ct_pc4', name: 'Gyro', price: '', description: '', menuType: 'Catering', section: 'Protein Choice' },
  { id: 'ct_pc5', name: 'Kafta Kabob', price: '', description: '', menuType: 'Catering', section: 'Protein Choice' },
  { id: 'ct_pc6', name: 'Salmon Kabob', price: '+$3', description: '', menuType: 'Catering', section: 'Protein Choice' },
  { id: 'ct_pc7', name: 'Shrimp Kabob', price: '+$3', description: '', menuType: 'Catering', section: 'Protein Choice' },

  // SIDE CHOICE
  { id: 'ct_sc1', name: 'Tumeric Rice', price: '', description: '', menuType: 'Catering', section: 'Side Choice' },
  { id: 'ct_sc2', name: 'Hummus', price: '', description: '', menuType: 'Catering', section: 'Side Choice' },
  { id: 'ct_sc3', name: 'Spicy Hummus', price: '+$1', description: '', menuType: 'Catering', section: 'Side Choice' },
  { id: 'ct_sc4', name: 'Tzatziki', price: '+$1.5', description: '', menuType: 'Catering', section: 'Side Choice' },
  { id: 'ct_sc5', name: 'Baba Ghanoush', price: '+$1.5', description: '', menuType: 'Catering', section: 'Side Choice' },

  // SALAD CHOICE
  { id: 'ct_sl1', name: 'House Salad', price: '', description: '', menuType: 'Catering', section: 'Salad Choice' },
  { id: 'ct_sl2', name: 'Tabbouleh', price: '+$1.5', description: '', menuType: 'Catering', section: 'Salad Choice' },
  { id: 'ct_sl3', name: 'Greek Salad', price: '+$1.5', description: '', menuType: 'Catering', section: 'Salad Choice' },
  { id: 'ct_sl4', name: 'Beet Salad', price: '+$1.5', description: '', menuType: 'Catering', section: 'Salad Choice' },

  // PARTY TRAYS TO GO
  { id: 'ct_pt1', name: 'Baba Ghanoush', price: '$33', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt2', name: 'Hummus & Pita', price: '$31', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt3', name: 'Spicy Hummus', price: '$36', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt4', name: 'Greek Salad', price: '$42', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt5', name: 'House Salad', price: '$28', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt6', name: 'Beet Salad', price: '$54', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt7', name: 'Tabbouleh', price: '$42', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt8', name: 'Tzatziki', price: '$33', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt9', name: 'Rice', price: '$28', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt10', name: 'Falafel (24 pc)', price: '$34', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt11', name: 'Grape Leaves (24 pc)', price: '$42', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt12', name: 'Baklava (12 pc)', price: '$54', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt13', name: 'Pita (Per Piece)', price: '$2', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt14', name: 'Pappardelle', price: '$190', description: 'Short rib & porcini mushroom ragu', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt15', name: 'Bucatini Cacio e Pepe*', price: '$150', description: 'Black pepper & pecorino romano', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt16', name: 'Spaghetti with Little Neck Clams*', price: '$190', description: 'Chili garlic butter with white wine', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt17', name: 'Bolognese*', price: '$160', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt18', name: 'Fettuccine Alfredo w/ Chicken*', price: '$90', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt19', name: 'Penne with Pink Sauce*', price: '$100', description: '', menuType: 'Catering', section: 'Party Trays To Go' },
  { id: 'ct_pt20', name: 'Panini Tray', price: '$120', description: 'Choose 7 Full Paninis Cut Into Halves With Caesar Salad (Feeds 10 - 12)', menuType: 'Catering', section: 'Party Trays To Go' },
];

export const EVENTS: EventItem[] = [
  { id: 'e1', title: 'For Her & I', date: 'Feb 14th, 4:00 PM - 10:00 PM', description: 'Celebrate love this Valentines Day at The Green Olive Bar & Grill', image: '/ForHer&I.png' }
];

export const GALLERY: GalleryImage[] = [
  { id: 'g1', url: '/gallery/craigrootimaging_GO-103-150x150.jpg', caption: 'craigrootimaging_GO-103-150x150.jpg' },
  { id: 'g2', url: '/gallery/craigrootimaging_GO-105-150x150.jpg', caption: 'craigrootimaging_GO-105-150x150.jpg' },
  { id: 'g3', url: '/gallery/craigrootimaging_GO-106-150x150.jpg', caption: 'craigrootimaging_GO-106-150x150.jpg' },
  { id: 'g4', url: '/gallery/craigrootimaging_GO-107-scaled.jpg', caption: 'craigrootimaging_GO-107-scaled.jpg' },
  { id: 'g5', url: '/gallery/craigrootimaging_GO-111-150x150.jpg', caption: 'craigrootimaging_GO-111-150x150.jpg' },
  { id: 'g6', url: '/gallery/craigrootimaging_GO-112.jpg', caption: 'craigrootimaging_GO-112.jpg' },
  { id: 'g7', url: '/gallery/craigrootimaging_GO-117-1536x1025.jpg', caption: 'craigrootimaging_GO-117-1536x1025.jpg' },
  { id: 'g8', url: '/gallery/craigrootimaging_GO-119-150x150.jpg', caption: 'craigrootimaging_GO-119-150x150.jpg' },
  { id: 'g9', url: '/gallery/craigrootimaging_GO-121-768x512.jpg', caption: 'craigrootimaging_GO-121-768x512.jpg' },
  { id: 'g10', url: '/gallery/craigrootimaging_GO-123-150x150.jpg', caption: 'craigrootimaging_GO-123-150x150.jpg' },
  { id: 'g11', url: '/gallery/craigrootimaging_GO-127-1024x683.jpg', caption: 'craigrootimaging_GO-127-1024x683.jpg' },
  { id: 'g12', url: '/gallery/craigrootimaging_GO-13-768x513.jpg', caption: 'craigrootimaging_GO-13-768x513.jpg' },
  { id: 'g13', url: '/gallery/craigrootimaging_GO-134-768x512.jpg', caption: 'craigrootimaging_GO-134-768x512.jpg' },
  { id: 'g14', url: '/gallery/craigrootimaging_GO-137-1024x683.jpg', caption: 'craigrootimaging_GO-137-1024x683.jpg' },
  { id: 'g15', url: '/gallery/craigrootimaging_GO-139-150x150.jpg', caption: 'craigrootimaging_GO-139-150x150.jpg' },
  { id: 'g16', url: '/gallery/craigrootimaging_GO-142-768x512.jpg', caption: 'craigrootimaging_GO-142-768x512.jpg' },
  { id: 'g17', url: '/gallery/craigrootimaging_GO-144-150x150.jpg', caption: 'craigrootimaging_GO-144-150x150.jpg' },
  { id: 'g18', url: '/gallery/craigrootimaging_GO-145-150x150.jpg', caption: 'craigrootimaging_GO-145-150x150.jpg' },
  { id: 'g19', url: '/gallery/craigrootimaging_GO-151.jpg', caption: 'craigrootimaging_GO-151.jpg' },
  { id: 'g20', url: '/gallery/craigrootimaging_GO-153-2048x1366.jpg', caption: 'craigrootimaging_GO-153-2048x1366.jpg' },
  { id: 'g21', url: '/gallery/craigrootimaging_GO-155-150x150.jpg', caption: 'craigrootimaging_GO-155-150x150.jpg' },
  { id: 'g22', url: '/gallery/craigrootimaging_GO-159-1024x683.jpg', caption: 'craigrootimaging_GO-159-1024x683.jpg' },
  { id: 'g23', url: '/gallery/craigrootimaging_GO-161-768x512.jpg', caption: 'craigrootimaging_GO-161-768x512.jpg' },
  { id: 'g24', url: '/gallery/craigrootimaging_GO-167-150x150.jpg', caption: 'craigrootimaging_GO-167-150x150.jpg' },
  { id: 'g25', url: '/gallery/craigrootimaging_GO-169-300x200.jpg', caption: 'craigrootimaging_GO-169-300x200.jpg' },
  { id: 'g26', url: '/gallery/craigrootimaging_GO-174.jpg', caption: 'craigrootimaging_GO-174.jpg' },
  { id: 'g27', url: '/gallery/craigrootimaging_GO-177.jpg', caption: 'craigrootimaging_GO-177.jpg' },
  { id: 'g28', url: '/gallery/craigrootimaging_GO-178.jpg', caption: 'craigrootimaging_GO-178.jpg' },
  { id: 'g29', url: '/gallery/craigrootimaging_GO-179-150x150.jpg', caption: 'craigrootimaging_GO-179-150x150.jpg' },
  { id: 'g30', url: '/gallery/craigrootimaging_GO-183-300x200.jpg', caption: 'craigrootimaging_GO-183-300x200.jpg' },
  { id: 'g31', url: '/gallery/craigrootimaging_GO-185-768x512.jpg', caption: 'craigrootimaging_GO-185-768x512.jpg' },
  { id: 'g32', url: '/gallery/craigrootimaging_GO-191-2048x1366.jpg', caption: 'craigrootimaging_GO-191-2048x1366.jpg' },
  { id: 'g33', url: '/gallery/craigrootimaging_GO-193-150x150.jpg', caption: 'craigrootimaging_GO-193-150x150.jpg' },
  { id: 'g34', url: '/gallery/craigrootimaging_GO-196-150x150.jpg', caption: 'craigrootimaging_GO-196-150x150.jpg' },
  { id: 'g35', url: '/gallery/craigrootimaging_GO-199-2048x1366.jpg', caption: 'craigrootimaging_GO-199-2048x1366.jpg' },
  { id: 'g36', url: '/gallery/craigrootimaging_GO-202-150x150.jpg', caption: 'craigrootimaging_GO-202-150x150.jpg' },
  { id: 'g37', url: '/gallery/craigrootimaging_GO-204-1536x1025.jpg', caption: 'craigrootimaging_GO-204-1536x1025.jpg' },
  { id: 'g38', url: '/gallery/craigrootimaging_GO-206-1024x683.jpg', caption: 'craigrootimaging_GO-206-1024x683.jpg' },
  { id: 'g39', url: '/gallery/craigrootimaging_GO-21-300x200.jpg', caption: 'craigrootimaging_GO-21-300x200.jpg' },
  { id: 'g40', url: '/gallery/craigrootimaging_GO-214-150x150.jpg', caption: 'craigrootimaging_GO-214-150x150.jpg' },
  { id: 'g1', url: '/gal/craigrootimaging_GO-105-2048x1366.jpg', caption: '' },
  { id: 'g2', url: '/gal/craigrootimaging_GO-106-2048x1366.jpg', caption: '' },
  { id: 'g3', url: '/gal/craigrootimaging_GO-110-2048x1366.jpg', caption: '' },
  { id: 'g4', url: '/gal/craigrootimaging_GO-111-2048x1366.jpg', caption: '' },
  { id: 'g5', url: '/gal/craigrootimaging_GO-112-2048x1366.jpg', caption: '' },
  { id: 'g6', url: '/gal/craigrootimaging_GO-115-2048x1366.jpg', caption: '' },
  { id: 'g7', url: '/gal/craigrootimaging_GO-117-scaled.jpg', caption: '' },
  { id: 'g8', url: '/gal/craigrootimaging_GO-118-2048x1366.jpg', caption: '' },
  { id: 'g9', url: '/gal/craigrootimaging_GO-119-2048x1366.jpg', caption: '' },
  { id: 'g10', url: '/gal/craigrootimaging_GO-120-2048x1366.jpg', caption: '' },
  { id: 'g11', url: '/gal/craigrootimaging_GO-121-2048x1366.jpg', caption: '' },
  { id: 'g12', url: '/gal/craigrootimaging_GO-123-2048x1366.jpg', caption: '' },
  { id: 'g13', url: '/gal/craigrootimaging_GO-124-2048x1366.jpg', caption: '' },
  { id: 'g14', url: '/gal/craigrootimaging_GO-125-2048x1366.jpg', caption: '' },
  { id: 'g15', url: '/gal/craigrootimaging_GO-126-2048x1366.jpg', caption: '' },
  { id: 'g16', url: '/gal/craigrootimaging_GO-127-2048x1366.jpg', caption: '' },
  { id: 'g17', url: '/gal/craigrootimaging_GO-13-2048x1368.jpg', caption: '' },
  { id: 'g18', url: '/gal/craigrootimaging_GO-131-2048x1366.jpg', caption: '' },
  { id: 'g19', url: '/gal/craigrootimaging_GO-132-2048x1366.jpg', caption: '' },
  { id: 'g20', url: '/gal/craigrootimaging_GO-134-2048x1366.jpg', caption: '' },
  { id: 'g21', url: '/gal/craigrootimaging_GO-137-2048x1366.jpg', caption: '' },
  { id: 'g22', url: '/gal/craigrootimaging_GO-138-2048x1366.jpg', caption: '' },
  { id: 'g23', url: '/gal/craigrootimaging_GO-139-2048x1366.jpg', caption: '' },
  { id: 'g24', url: '/gal/craigrootimaging_GO-140-2048x1366.jpg', caption: '' },
  { id: 'g25', url: '/gal/craigrootimaging_GO-141-2048x1366.jpg', caption: '' },
  { id: 'g26', url: '/gal/craigrootimaging_GO-142-2048x1366.jpg', caption: '' },
  { id: 'g27', url: '/gal/craigrootimaging_GO-143-2048x1366.jpg', caption: '' },
  { id: 'g28', url: '/gal/craigrootimaging_GO-144-2048x1366.jpg', caption: '' },
  { id: 'g29', url: '/gal/craigrootimaging_GO-146-2048x1366.jpg', caption: '' },
  { id: 'g30', url: '/gal/craigrootimaging_GO-151-2048x1366.jpg', caption: '' },
  { id: 'g31', url: '/gal/craigrootimaging_GO-152-2048x1366.jpg', caption: '' },
  { id: 'g32', url: '/gal/craigrootimaging_GO-154-2048x1366.jpg', caption: '' },
  { id: 'g33', url: '/gal/craigrootimaging_GO-155-2048x1366.jpg', caption: '' },
  { id: 'g34', url: '/gal/craigrootimaging_GO-159-2048x1366.jpg', caption: '' },
  { id: 'g35', url: '/gal/craigrootimaging_GO-161-2048x1366.jpg', caption: '' },
  { id: 'g36', url: '/gal/craigrootimaging_GO-165-2048x1366.jpg', caption: '' },
  { id: 'g37', url: '/gal/craigrootimaging_GO-167-2048x1366.jpg', caption: '' },
  { id: 'g38', url: '/gal/craigrootimaging_GO-17-2048x1366.jpg', caption: '' },
  { id: 'g39', url: '/gal/craigrootimaging_GO-174-2048x1366.jpg', caption: '' },
  { id: 'g40', url: '/gal/craigrootimaging_GO-176-2048x1366.jpg', caption: '' },
  { id: 'g41', url: '/gal/craigrootimaging_GO-177-2048x1366.jpg', caption: '' },
  { id: 'g42', url: '/gal/craigrootimaging_GO-178-2048x1366.jpg', caption: '' },
  { id: 'g43', url: '/gal/craigrootimaging_GO-183-2048x1366.jpg', caption: '' },
  { id: 'g44', url: '/gal/craigrootimaging_GO-185-2048x1366.jpg', caption: '' },
  { id: 'g45', url: '/gal/craigrootimaging_GO-186-2048x1366.jpg', caption: '' },
  { id: 'g46', url: '/gal/craigrootimaging_GO-187-2048x1366.jpg', caption: '' },
  { id: 'g47', url: '/gal/craigrootimaging_GO-188-2048x1366.jpg', caption: '' },
  { id: 'g48', url: '/gal/craigrootimaging_GO-190-2048x1366.jpg', caption: '' },
  { id: 'g49', url: '/gal/craigrootimaging_GO-191-2048x1366.jpg', caption: '' },
  { id: 'g50', url: '/gal/craigrootimaging_GO-192-2048x1366.jpg', caption: '' },
  { id: 'g51', url: '/gal/craigrootimaging_GO-193-2048x1366.jpg', caption: '' },
  { id: 'g52', url: '/gal/craigrootimaging_GO-194-2048x1366.jpg', caption: '' },
  { id: 'g53', url: '/gal/craigrootimaging_GO-196-2048x1366.jpg', caption: '' },
  { id: 'g54', url: '/gal/craigrootimaging_GO-198-2048x1366.jpg', caption: '' },
  { id: 'g55', url: '/gal/craigrootimaging_GO-199-2048x1366.jpg', caption: '' },
  { id: 'g56', url: '/gal/craigrootimaging_GO-202-2048x1366.jpg', caption: '' },
  { id: 'g57', url: '/gal/craigrootimaging_GO-204-2048x1366.jpg', caption: '' },
  { id: 'g58', url: '/gal/craigrootimaging_GO-206-2048x1366.jpg', caption: '' },
  { id: 'g59', url: '/gal/craigrootimaging_GO-21-2048x1366.jpg', caption: '' },
  { id: 'g60', url: '/gal/craigrootimaging_GO-219-2048x1366.jpg', caption: '' },
  { id: 'g61', url: '/gal/craigrootimaging_GO-221-2048x1366.jpg', caption: '' },
  { id: 'g62', url: '/gal/craigrootimaging_GO-225-2048x1366.jpg', caption: '' },
  { id: 'g63', url: '/gal/craigrootimaging_GO-227-2048x1366.jpg', caption: '' },
  { id: 'g64', url: '/gal/craigrootimaging_GO-228-2048x1366.jpg', caption: '' },
  { id: 'g65', url: '/gal/craigrootimaging_GO-230-2048x1366.jpg', caption: '' },
  { id: 'g66', url: '/gal/craigrootimaging_GO-231-2048x1366.jpg', caption: '' },
  { id: 'g67', url: '/gal/craigrootimaging_GO-236-2048x1366.jpg', caption: '' },
  { id: 'g68', url: '/gal/craigrootimaging_GO-237-2048x1366.jpg', caption: '' },
  { id: 'g69', url: '/gal/craigrootimaging_GO-239-2048x1366.jpg', caption: '' },
  { id: 'g70', url: '/gal/craigrootimaging_GO-243-2048x1366.jpg', caption: '' },
  { id: 'g71', url: '/gal/craigrootimaging_GO-246-2048x1366.jpg', caption: '' },
  { id: 'g72', url: '/gal/craigrootimaging_GO-247-2048x1366.jpg', caption: '' },
  { id: 'g73', url: '/gal/craigrootimaging_GO-248-2048x1366.jpg', caption: '' },
  { id: 'g74', url: '/gal/craigrootimaging_GO-25-2048x1366.jpg', caption: '' },
  { id: 'g75', url: '/gal/craigrootimaging_GO-251-2048x1366.jpg', caption: '' },
  { id: 'g76', url: '/gal/craigrootimaging_GO-252-2048x1366.jpg', caption: '' },
  { id: 'g77', url: '/gal/craigrootimaging_GO-254-2048x1366.jpg', caption: '' },
  { id: 'g78', url: '/gal/craigrootimaging_GO-255-2048x1366.jpg', caption: '' },
  { id: 'g79', url: '/gal/craigrootimaging_GO-260-2048x1366.jpg', caption: '' },
  { id: 'g80', url: '/gal/craigrootimaging_GO-261-2048x1366.jpg', caption: '' },
  { id: 'g81', url: '/gal/craigrootimaging_GO-262-scaled.jpg', caption: '' },
  { id: 'g82', url: '/gal/craigrootimaging_GO-263-2048x1366.jpg', caption: '' },
  { id: 'g83', url: '/gal/craigrootimaging_GO-264-2048x1366.jpg', caption: '' },
  { id: 'g84', url: '/gal/craigrootimaging_GO-265-scaled.jpg', caption: '' },
  { id: 'g85', url: '/gal/craigrootimaging_GO-266-2048x1366.jpg', caption: '' },
  { id: 'g86', url: '/gal/craigrootimaging_GO-267-2048x1366.jpg', caption: '' },
  { id: 'g87', url: '/gal/craigrootimaging_GO-268-2048x1366.jpg', caption: '' },
  { id: 'g88', url: '/gal/craigrootimaging_GO-270-2048x1366.jpg', caption: '' },
  { id: 'g89', url: '/gal/craigrootimaging_GO-271-2048x1366.jpg', caption: '' },
  { id: 'g90', url: '/gal/craigrootimaging_GO-273-2048x1366.jpg', caption: '' },
  { id: 'g91', url: '/gal/craigrootimaging_GO-278-2048x1366.jpg', caption: '' },
  { id: 'g92', url: '/gal/craigrootimaging_GO-281-2048x1366.jpg', caption: '' },
  { id: 'g93', url: '/gal/craigrootimaging_GO-282-2048x1366.jpg', caption: '' },
  { id: 'g94', url: '/gal/craigrootimaging_GO-285-2048x1366.jpg', caption: '' },
  { id: 'g95', url: '/gal/craigrootimaging_GO-29-2048x1366.jpg', caption: '' },
  { id: 'g96', url: '/gal/craigrootimaging_GO-290-2048x1366.jpg', caption: '' },
  { id: 'g97', url: '/gal/craigrootimaging_GO-292-2048x1366.jpg', caption: '' },
  { id: 'g98', url: '/gal/craigrootimaging_GO-293-2048x1366.jpg', caption: '' },
  { id: 'g99', url: '/gal/craigrootimaging_GO-298-2048x1366.jpg', caption: '' },
  { id: 'g100', url: '/gal/craigrootimaging_GO-3-2048x1366.jpg', caption: '' },
  { id: 'g101', url: '/gal/craigrootimaging_GO-301-2048x1366.jpg', caption: '' },
  { id: 'g102', url: '/gal/craigrootimaging_GO-302-2048x1366.jpg', caption: '' },
  { id: 'g103', url: '/gal/craigrootimaging_GO-31-2048x1366.jpg', caption: '' },
  { id: 'g104', url: '/gal/craigrootimaging_GO-310-2048x1366.jpg', caption: '' },
  { id: 'g105', url: '/gal/craigrootimaging_GO-316-2048x1366.jpg', caption: '' },
  { id: 'g106', url: '/gal/craigrootimaging_GO-317-2048x1366.jpg', caption: '' },
  { id: 'g107', url: '/gal/craigrootimaging_GO-326-2048x1366.jpg', caption: '' },
  { id: 'g108', url: '/gal/craigrootimaging_GO-327-2048x1366.jpg', caption: '' },
  { id: 'g109', url: '/gal/craigrootimaging_GO-330-2048x1366.jpg', caption: '' },
  { id: 'g110', url: '/gal/craigrootimaging_GO-331-2048x1366.jpg', caption: '' },
  { id: 'g111', url: '/gal/craigrootimaging_GO-333-2048x1366.jpg', caption: '' },
  { id: 'g112', url: '/gal/craigrootimaging_GO-334-2048x1366.jpg', caption: '' },
  { id: 'g113', url: '/gal/craigrootimaging_GO-335-2048x1366.jpg', caption: '' },
  { id: 'g114', url: '/gal/craigrootimaging_GO-336-2048x1366.jpg', caption: '' },
  { id: 'g115', url: '/gal/craigrootimaging_GO-337-2048x1366.jpg', caption: '' },
  { id: 'g116', url: '/gal/craigrootimaging_GO-338-2048x1366.jpg', caption: '' },
  { id: 'g117', url: '/gal/craigrootimaging_GO-339-2048x1366.jpg', caption: '' },
  { id: 'g118', url: '/gal/craigrootimaging_GO-346-2048x1366.jpg', caption: '' },
  { id: 'g119', url: '/gal/craigrootimaging_GO-347-2048x1366.jpg', caption: '' },
  { id: 'g120', url: '/gal/craigrootimaging_GO-348-2048x1366.jpg', caption: '' },
  { id: 'g121', url: '/gal/craigrootimaging_GO-349-2048x1366.jpg', caption: '' },
  { id: 'g122', url: '/gal/craigrootimaging_GO-35-2048x1366.jpg', caption: '' },
  { id: 'g123', url: '/gal/craigrootimaging_GO-350-2048x1366.jpg', caption: '' },
  { id: 'g124', url: '/gal/craigrootimaging_GO-353-2048x1366.jpg', caption: '' },
  { id: 'g125', url: '/gal/craigrootimaging_GO-354-2048x1366.jpg', caption: '' },
  { id: 'g126', url: '/gal/craigrootimaging_GO-36-2048x1366.jpg', caption: '' },
  { id: 'g127', url: '/gal/craigrootimaging_GO-361-2048x1366.jpg', caption: '' },
  { id: 'g128', url: '/gal/craigrootimaging_GO-365-2048x1366.jpg', caption: '' },
  { id: 'g129', url: '/gal/craigrootimaging_GO-368-2048x1366.jpg', caption: '' },
  { id: 'g130', url: '/gal/craigrootimaging_GO-37-2048x1366.jpg', caption: '' },
  { id: 'g131', url: '/gal/craigrootimaging_GO-376-2048x1366.jpg', caption: '' },
  { id: 'g132', url: '/gal/craigrootimaging_GO-377-2048x1366.jpg', caption: '' },
  { id: 'g133', url: '/gal/craigrootimaging_GO-38-2048x1366.jpg', caption: '' },
  { id: 'g134', url: '/gal/craigrootimaging_GO-381-2048x1366.jpg', caption: '' },
  { id: 'g135', url: '/gal/craigrootimaging_GO-383-scaled.jpg', caption: '' },
  { id: 'g136', url: '/gal/craigrootimaging_GO-384-scaled.jpg', caption: '' },
  { id: 'g137', url: '/gal/craigrootimaging_GO-385-scaled.jpg', caption: '' },
  { id: 'g138', url: '/gal/craigrootimaging_GO-39-2048x1366.jpg', caption: '' },
  { id: 'g139', url: '/gal/craigrootimaging_GO-40-2048x1366.jpg', caption: '' },
  { id: 'g140', url: '/gal/craigrootimaging_GO-402-2048x1366.jpg', caption: '' },
  { id: 'g141', url: '/gal/craigrootimaging_GO-407-2048x1366.jpg', caption: '' },
  { id: 'g142', url: '/gal/craigrootimaging_GO-41-2048x1366.jpg', caption: '' },
  { id: 'g143', url: '/gal/craigrootimaging_GO-410-2048x1366.jpg', caption: '' },
  { id: 'g144', url: '/gal/craigrootimaging_GO-411-2048x1366.jpg', caption: '' },
  { id: 'g145', url: '/gal/craigrootimaging_GO-413-2048x1366.jpg', caption: '' },
  { id: 'g146', url: '/gal/craigrootimaging_GO-417-2048x1366.jpg', caption: '' },
  { id: 'g147', url: '/gal/craigrootimaging_GO-419-2048x1366.jpg', caption: '' },
  { id: 'g148', url: '/gal/craigrootimaging_GO-43-2048x1366.jpg', caption: '' },
  { id: 'g149', url: '/gal/craigrootimaging_GO-46-2048x1366.jpg', caption: '' },
  { id: 'g150', url: '/gal/craigrootimaging_GO-55-2048x1366.jpg', caption: '' },
  { id: 'g151', url: '/gal/craigrootimaging_GO-60-2048x1366.jpg', caption: '' },
  { id: 'g152', url: '/gal/craigrootimaging_GO-62-2048x1366.jpg', caption: '' },
  { id: 'g153', url: '/gal/craigrootimaging_GO-68-2048x1366.jpg', caption: '' },
  { id: 'g154', url: '/gal/craigrootimaging_GO-7-2048x1366.jpg', caption: '' },
  { id: 'g155', url: '/gal/craigrootimaging_GO-76-2048x1366.jpg', caption: '' },
  { id: 'g156', url: '/gal/craigrootimaging_GO-8-2048x1366.jpg', caption: '' },
  { id: 'g157', url: '/gal/craigrootimaging_GO-80-2048x1366.jpg', caption: '' },
  { id: 'g158', url: '/gal/craigrootimaging_GO-83-2048x1366.jpg', caption: '' },
  { id: 'g159', url: '/gal/craigrootimaging_GO-85-2048x1366.jpg', caption: '' },
  { id: 'g160', url: '/gal/craigrootimaging_GO-88-2048x1366.jpg', caption: '' },
  { id: 'g161', url: '/gal/craigrootimaging_GO-91-2048x1366.jpg', caption: '' },
  { id: 'g162', url: '/gal/craigrootimaging_GO-92-2048x1366.jpg', caption: '' },
  { id: 'g163', url: '/gal/craigrootimaging_GO-95-2048x1366.jpg', caption: '' },
  { id: 'g164', url: '/gal/craigrootimaging_GO-97-scaled.jpg', caption: '' },
  { id: 'g165', url: '/gal/craigrootimaging_GO-98-2048x1366.jpg', caption: '' },
  { id: 'g166', url: '/gal/IMG_4691.jpg', caption: '' },
  { id: 'g167', url: '/gal/IMG_4699.jpg', caption: '' },
  { id: 'g168', url: '/gal/IMG_4701.jpg', caption: '' },
  { id: 'g169', url: '/gal/IMG_4705.jpg', caption: '' },
  { id: 'g62', url: '/gallery/craigrootimaging_GO-271-2048x1366.jpg', caption: 'craigrootimaging_GO-271-2048x1366.jpg' },
  { id: 'g63', url: '/gallery/craigrootimaging_GO-273-768x512.jpg', caption: 'craigrootimaging_GO-273-768x512.jpg' },
  { id: 'g64', url: '/gallery/craigrootimaging_GO-276-300x200.jpg', caption: 'craigrootimaging_GO-276-300x200.jpg' },
  { id: 'g65', url: '/gallery/craigrootimaging_GO-278-1536x1025.jpg', caption: 'craigrootimaging_GO-278-1536x1025.jpg' },
  { id: 'g66', url: '/gallery/craigrootimaging_GO-280.jpg', caption: 'craigrootimaging_GO-280.jpg' },
  { id: 'g67', url: '/gallery/craigrootimaging_GO-282-300x200.jpg', caption: 'craigrootimaging_GO-282-300x200.jpg' },
  { id: 'g68', url: '/gallery/craigrootimaging_GO-284-150x150.jpg', caption: 'craigrootimaging_GO-284-150x150.jpg' },
  { id: 'g69', url: '/gallery/craigrootimaging_GO-29.jpg', caption: 'craigrootimaging_GO-29.jpg' },
  { id: 'g70', url: '/gallery/craigrootimaging_GO-290-scaled.jpg', caption: 'craigrootimaging_GO-290-scaled.jpg' },
  { id: 'g71', url: '/gallery/craigrootimaging_GO-292-768x512.jpg', caption: 'craigrootimaging_GO-292-768x512.jpg' },
  { id: 'g72', url: '/gallery/craigrootimaging_GO-293-1536x1025.jpg', caption: 'craigrootimaging_GO-293-1536x1025.jpg' },
  { id: 'g73', url: '/gallery/craigrootimaging_GO-295.jpg', caption: 'craigrootimaging_GO-295.jpg' },
  { id: 'g74', url: '/gallery/craigrootimaging_GO-298-150x150.jpg', caption: 'craigrootimaging_GO-298-150x150.jpg' },
  { id: 'g75', url: '/gallery/craigrootimaging_GO-3-2048x1366.jpg', caption: 'craigrootimaging_GO-3-2048x1366.jpg' },
  { id: 'g76', url: '/gallery/craigrootimaging_GO-303-300x200.jpg', caption: 'craigrootimaging_GO-303-300x200.jpg' },
  { id: 'g77', url: '/gallery/craigrootimaging_GO-306-150x150.jpg', caption: 'craigrootimaging_GO-306-150x150.jpg' },
  { id: 'g78', url: '/gallery/craigrootimaging_GO-31-300x200.jpg', caption: 'craigrootimaging_GO-31-300x200.jpg' },
  { id: 'g79', url: '/gallery/craigrootimaging_GO-310-150x150.jpg', caption: 'craigrootimaging_GO-310-150x150.jpg' },
  { id: 'g80', url: '/gallery/craigrootimaging_GO-315-768x512.jpg', caption: 'craigrootimaging_GO-315-768x512.jpg' },
  { id: 'g81', url: '/gallery/craigrootimaging_GO-316-150x150.jpg', caption: 'craigrootimaging_GO-316-150x150.jpg' },
  { id: 'g82', url: '/gallery/craigrootimaging_GO-317-1536x1025.jpg', caption: 'craigrootimaging_GO-317-1536x1025.jpg' },
  { id: 'g83', url: '/gallery/craigrootimaging_GO-322-2048x1366.jpg', caption: 'craigrootimaging_GO-322-2048x1366.jpg' },
  { id: 'g84', url: '/gallery/craigrootimaging_GO-329-150x150.jpg', caption: 'craigrootimaging_GO-329-150x150.jpg' },
  { id: 'g85', url: '/gallery/craigrootimaging_GO-332-150x150.jpg', caption: 'craigrootimaging_GO-332-150x150.jpg' },
  { id: 'g86', url: '/gallery/craigrootimaging_GO-333-300x200.jpg', caption: 'craigrootimaging_GO-333-300x200.jpg' },
  { id: 'g87', url: '/gallery/craigrootimaging_GO-335-150x150.jpg', caption: 'craigrootimaging_GO-335-150x150.jpg' },
  { id: 'g88', url: '/gallery/craigrootimaging_GO-336-1024x683.jpg', caption: 'craigrootimaging_GO-336-1024x683.jpg' },
  { id: 'g89', url: '/gallery/craigrootimaging_GO-337-768x512.jpg', caption: 'craigrootimaging_GO-337-768x512.jpg' },
  { id: 'g90', url: '/gallery/craigrootimaging_GO-338-2048x1366.jpg', caption: 'craigrootimaging_GO-338-2048x1366.jpg' },
  { id: 'g91', url: '/gallery/craigrootimaging_GO-339-scaled.jpg', caption: 'craigrootimaging_GO-339-scaled.jpg' },
  { id: 'g92', url: '/gallery/craigrootimaging_GO-35-768x512.jpg', caption: 'craigrootimaging_GO-35-768x512.jpg' },
  { id: 'g93', url: '/gallery/craigrootimaging_GO-350.jpg', caption: 'craigrootimaging_GO-350.jpg' },
  { id: 'g94', url: '/gallery/craigrootimaging_GO-353-150x150.jpg', caption: 'craigrootimaging_GO-353-150x150.jpg' },
  { id: 'g95', url: '/gallery/craigrootimaging_GO-354-1024x683.jpg', caption: 'craigrootimaging_GO-354-1024x683.jpg' },
  { id: 'g96', url: '/gallery/craigrootimaging_GO-36-scaled.jpg', caption: 'craigrootimaging_GO-36-scaled.jpg' },
  { id: 'g97', url: '/gallery/craigrootimaging_GO-361-150x150.jpg', caption: 'craigrootimaging_GO-361-150x150.jpg' },
  { id: 'g98', url: '/gallery/craigrootimaging_GO-365-150x150.jpg', caption: 'craigrootimaging_GO-365-150x150.jpg' },
  { id: 'g99', url: '/gallery/craigrootimaging_GO-368-150x150.jpg', caption: 'craigrootimaging_GO-368-150x150.jpg' },
  { id: 'g100', url: '/gallery/craigrootimaging_GO-37-scaled.jpg', caption: 'craigrootimaging_GO-37-scaled.jpg' },
  { id: 'g101', url: '/gallery/craigrootimaging_GO-375-150x150.jpg', caption: 'craigrootimaging_GO-375-150x150.jpg' },
  { id: 'g102', url: '/gallery/craigrootimaging_GO-378-2048x1366.jpg', caption: 'craigrootimaging_GO-378-2048x1366.jpg' },
  { id: 'g103', url: '/gallery/craigrootimaging_GO-38-1536x1025.jpg', caption: 'craigrootimaging_GO-38-1536x1025.jpg' },
  { id: 'g104', url: '/gallery/craigrootimaging_GO-382.jpg', caption: 'craigrootimaging_GO-382.jpg' },
  { id: 'g105', url: '/gallery/craigrootimaging_GO-383-200x300.jpg', caption: 'craigrootimaging_GO-383-200x300.jpg' },
  { id: 'g106', url: '/gallery/craigrootimaging_GO-384-200x300.jpg', caption: 'craigrootimaging_GO-384-200x300.jpg' },
  { id: 'g107', url: '/gallery/craigrootimaging_GO-385-scaled.jpg', caption: 'craigrootimaging_GO-385-scaled.jpg' },
  { id: 'g108', url: '/gallery/craigrootimaging_GO-388-768x512.jpg', caption: 'craigrootimaging_GO-388-768x512.jpg' },
  { id: 'g109', url: '/gallery/craigrootimaging_GO-402-150x150.jpg', caption: 'craigrootimaging_GO-402-150x150.jpg' },
  { id: 'g110', url: '/gallery/craigrootimaging_GO-403-scaled.jpg', caption: 'craigrootimaging_GO-403-scaled.jpg' },
  { id: 'g111', url: '/gallery/craigrootimaging_GO-410-1024x683.jpg', caption: 'craigrootimaging_GO-410-1024x683.jpg' },
  { id: 'g112', url: '/gallery/craigrootimaging_GO-44-scaled.jpg', caption: 'craigrootimaging_GO-44-scaled.jpg' },
  { id: 'g113', url: '/gallery/craigrootimaging_GO-47-scaled.jpg', caption: 'craigrootimaging_GO-47-scaled.jpg' },
  { id: 'g114', url: '/gallery/craigrootimaging_GO-51-2048x1366.jpg', caption: 'craigrootimaging_GO-51-2048x1366.jpg' },
  { id: 'g115', url: '/gallery/craigrootimaging_GO-55-150x150.jpg', caption: 'craigrootimaging_GO-55-150x150.jpg' },
  { id: 'g116', url: '/gallery/craigrootimaging_GO-59-150x150.jpg', caption: 'craigrootimaging_GO-59-150x150.jpg' },
  { id: 'g117', url: '/gallery/craigrootimaging_GO-61-150x150.jpg', caption: 'craigrootimaging_GO-61-150x150.jpg' },
  { id: 'g118', url: '/gallery/craigrootimaging_GO-67-200x300.jpg', caption: 'craigrootimaging_GO-67-200x300.jpg' },
  { id: 'g119', url: '/gallery/craigrootimaging_GO-7-150x150.jpg', caption: 'craigrootimaging_GO-7-150x150.jpg' },
  { id: 'g120', url: '/gallery/craigrootimaging_GO-70.jpg', caption: 'craigrootimaging_GO-70.jpg' },
  { id: 'g121', url: '/gallery/craigrootimaging_GO-76-1024x683.jpg', caption: 'craigrootimaging_GO-76-1024x683.jpg' },
  { id: 'g122', url: '/gallery/craigrootimaging_GO-79-150x150.jpg', caption: 'craigrootimaging_GO-79-150x150.jpg' },
  { id: 'g123', url: '/gallery/craigrootimaging_GO-80-1536x1025.jpg', caption: 'craigrootimaging_GO-80-1536x1025.jpg' },
  { id: 'g124', url: '/gallery/craigrootimaging_GO-83-300x200.jpg', caption: 'craigrootimaging_GO-83-300x200.jpg' },
  { id: 'g125', url: '/gallery/craigrootimaging_GO-84-1536x1025.jpg', caption: 'craigrootimaging_GO-84-1536x1025.jpg' },
  { id: 'g126', url: '/gallery/craigrootimaging_GO-88-150x150.jpg', caption: 'craigrootimaging_GO-88-150x150.jpg' },
  { id: 'g127', url: '/gallery/craigrootimaging_GO-92-1536x1025.jpg', caption: 'craigrootimaging_GO-92-1536x1025.jpg' },
  { id: 'g128', url: '/gallery/craigrootimaging_GO-95-1024x683.jpg', caption: 'craigrootimaging_GO-95-1024x683.jpg' },
  { id: 'g129', url: '/gallery/craigrootimaging_GO-97-683x1024.jpg', caption: 'craigrootimaging_GO-97-683x1024.jpg' },
  { id: 'g130', url: '/gallery/craigrootimaging_GO-99-scaled.jpg', caption: 'craigrootimaging_GO-99-scaled.jpg' },
];

export const ICONS = {
  Instagram: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="20" height="20" x="2" y="2" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/></svg>
  ),
  Facebook: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg>
  ),
  Phone: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>
  ),
  Mail: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
  ),
  MapPin: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>
  ),
  ArrowRight: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
  ),
  Yelp: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
      <path d="M7.5 2.1c-.5-.9-1.7-1.1-2.4-.3-.4.5-.4 1.2-.1 1.7l3.7 6.5c.3.5 1 .7 1.5.4.5-.3.7-1 .4-1.5L7.5 2.1zm9 0c.5-.9 1.7-1.1 2.4-.3.4.5.4 1.2.1 1.7l-3.7 6.5c-.3.5-1 .7-1.5.4-.5-.3-.7-1-.4-1.5l3.1-5.8zm5.4 7.6c1-.2 1.7 1 1.1 1.8l-5.1 5.1c-.4.4-1.1.4-1.5 0-.4-.4-.4-1.1 0-1.5l5.1-5.1c.2-.2.5-.3.8-.3zm-20.8 0c-1-.2-1.7 1-1.1 1.8l5.1 5.1c.4.4 1.1.4 1.5 0 .4-.4.4-1.1 0-1.5l-5.1-5.1c-.2-.2-.5-.3-.8-.3zm10.4 7.8c.6 0 1 .5 1 1.1v7.2c0 .6-.5 1.1-1.1 1.1-.6 0-1.1-.5-1.1-1.1v-7.2c0-.6.5-1.1 1.1-1.1z"/>
    </svg>
  ),
  Star: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="currentColor" stroke="none"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>
  )
};
